
const createTeam = team => {

    const generateManager = manager => {
        return `
 <div class="card text-black bg-info mb-3" style="max-width: 18rem;">
 <div class="card-header">${manager.getName()}</div>
 <div class="card-body">
   <h5 class="card-title">${manager.getRole()}</h5>
   <p class="card-text">
     <ul class="list-group">
         <li class="list-group-item">ID: ${manager.getId()}</li>
         <li class="list-group-item">Email: <a href="${manager.getEmail()}">${manager.getEmail()}</a></li>
         <li class="list-group-item">Office number: ${manager.getOfficeNumber()}</li>
     </ul>
 </div>
</div>
        `;
    };

    const generateEngineer = engineer => {
        return `
 <div class="card text-black bg-info mb-3" style="max-width: 18rem;">
 <div class="card-header">${engineer.getName()}</div>
 <div class="card-body">
   <h5 class="card-title">${engineer.getRole()}</h5>
   <p class="card-text">
     <ul class="list-group">
         <li class="list-group-item">ID: ${engineer.getId()}</li>
         <li class="list-group-item">Email: <a href="${engineer.getEmail()}">${engineer.getEmail()}</a></li>
         <li class="list-group-item">Github: <a href="${engineer.getGithub()}">${engineer.getGithub()}</a></li>
     </ul>
 </div>
</div>
        `;
    };
    const generateIntern = intern => {
        return `
 <div class="card text-black bg-info mb-3" style="max-width: 18rem;">
 <div class="card-header">${intern.getName()}</div>
 <div class="card-body">
   <h5 class="card-title">${intern.getRole()}</h5>
   <p class="card-text">
     <ul class="list-group">
         <li class="list-group-item">ID: ${intern.getId()}</li>
         <li class="list-group-item">Email: <a href="${intern.getEmail()}">${intern.getEmail()}</a></li>
         <li class="list-group-item">School: ${intern.getSchool()}</li>
     </ul>
 </div>
</div>
        `;
    };

    const html = [];

    html.push(team
        .filter(employee => employee.getRole() === "Manager")
        .map(manager => generateManager(manager))
    );
    html.push(team
        .filter(employee => employee.getRole() === "Engineer")
        .map(engineer => generateEngineer(engineer))
        .join("")
    );
    html.push(team
        .filter(employee => employee.getRole() === "Intern")
        .map(intern => generateIntern(intern))
        .join("")
    );

    return html.join("");
}

module.exports = team => {

    return `
    <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>My Team</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <script src="https://kit.fontawesome.com/c502137733.js"></script>
</head>

<body>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4 text-center">Team Mithers</h1>
          <p class="lead text-center">generated by Jayden</p>
        </div>
      </div>
    
      <div class="container">
        <div class="row">
      <div class="card text-black bg-info mb-3" style="max-width: 18rem;">
        ${createTeam(team)}
      </div>
    </div>
</div>


</body>
</html>


    `;
}